Config.cs, Trait.cs
The specific use case for this PR is that when trying to use this client in my own project, the `Config` class clashes with another `Config` class specified in my project. Therefore, I've added in the same namespace as what's defined in the other classes so that it won't clash going forward.
=> Add namespaces to avoid clashes with classes in consumer projects

BulletTrainClient.cs, BulletTrainConfiguration.cs, Config.cs, Feature.cs, Flag.cs, Identity.cs, README.md, Trait.cs, example/Program.cs
This pull request is dependent on https://github.com/BulletTrainHQ/bullet-train-dotnet-client/pull/3 as the namespace changes are included when making the style consistent across all files (there was a variation in style where 1 file used tabs, the other spaces).
When constructing the client, it is not possible (from what I saw) to specify the BulletTrain API url. This is a necessity for me as I am currently trying to host BulletTrain locally. I'd thought that others might be having the same problem which could discourage people from trying this client library. I'd recommend that if this pull request is accepted, it be released as a v2 as it breaks existing consumers when constructing an instance of the client.
I was not sure of the exact purpose of the `ServicePointManager` in the …
=> Allow API url to be defined when creating an instance of the BulletTrainClient

BulletTrainClient.cs, BulletTrainConfiguration.cs, UrlExtensions.cs
The issue is $"{configuration.ApiUrl}flags/" can end up in the wrong URL when `ApiUrl` doesn't end with `/`.
It's the same as with the path, it should be better to combine it properly.
=> fix: problems with configuration of API

BulletTrainClient.cs
update calling '/identities/{identifier}/' from deprecated version to actual API '/identities/?identifier=<identifier>' by API documentation https://api.bullet-train.io/api/v1/docs/
=> fix: update of calling deprecated API '/identities/{identifier}/'

BulletTrainClient.cs, BulletTrainConfiguration.cs, UrlExtensions.cs
`GetIdentitiesUrl` will help to distinguish between legacy and actual endpoint.
- It's set to use legacy by default to not break current usages.
#12
=> feat: bullet train client can use legacy identities and new ones

BulletTrainClient.cs
this avoids unhandled ArgumentNullExceptions coming from Newtonsoft.JsonSerializer
=> fix: return empty string instead of null when http request fails

BulletTrainClient.cs
Return default values when NullReferenceException would be thrown
=> fix: avoid null reference exceptions

BulletTrainClient.cs, bullet-train-dotnet-client.csproj
This way anyone using this client can distinguish if BT was not responding or if the FF value was false / zero
Changing version to 2.2.0 as return types were updated
=> feat: return null instead of default value for value types

Flagsmith.Client.Test/FlagsmithTest.cs, Flagsmith.Client.Test/HttpMocker.cs, Flagsmith.FlagsmithClient/FlagsmithClient.cs
If no traits are provided when requesting the flags for an identity, we should use a GET request instead of a POST request. 
Given the option now to cache GET identities and GET flags requests, this adds important functionality so that requests will use the cache if no traits are provided.
=> Use identity get request if no traits

Flagsmith.Client.Test/FlagsmithTest.cs, Flagsmith.FlagsmithClient/Cache/FlagListCache.cs, Flagsmith.FlagsmithClient/Cache/IdentityFlagListCache.cs, Flagsmith.FlagsmithClient/Cache/RegularFlagListCache.cs, Flagsmith.FlagsmithClient/Flags.cs, Flagsmith.FlagsmithClient/FlagsmithClient.cs
There was no need to initiate the cache right at the beginning. 
In fact, it was creating a problem trying to call `GetLatestFlags` on the cache that was currently trying to be initialized for the first time.
=> Fix cache initialisation that was some kind of circular reference.

Flagsmith.FlagsmithClient/FlagsmithClient.cs, Flagsmith.FlagsmithClient/PollingManager.cs
Ensures environment is retrieved on start polling by executing the StartPoll() method synchronoulsy, and executing the first call to the callback `GetAndUpdateEnvironmentFromApi` also asynchronoulsy and immediately. While(true) and Delay funcitons replaced by Timer class to allow the StartPoll() to be executed synchronously without hanging the execution of the main thread.
=> fix: Ensure environment is retrieved on start polling

Flagsmith.Client.Test/Fixtures.cs, Flagsmith.Client.Test/FlagsmithTest.cs, Flagsmith.Engine/Environment/Models/EnvironmentModel.cs, Flagsmith.Engine/Identity/Models/IdentityModel.cs, Flagsmith.FlagsmithClient/FlagsmithClient.cs
Contributes to https://github.com/Flagsmith/flagsmith/issues/3132.
Closes https://github.com/Flagsmith/flagsmith-dotnet-client/issues/89.
- Add support for environment-provided identities
- Remove unneeded integration configuration models
- Fix `IdentityModel.UpdateTraits` to support null traits
=> feat: Identity overrides in local evaluation mode

Flagsmith.Client.Test/AnalyticsProcessorTest.cs, Flagsmith.Client.Test/AnalyticsTests.cs, Flagsmith.Client.Test/Fixtures.cs, Flagsmith.Client.Test/FlagsmithTest.cs, Flagsmith.FlagsmithClient/AnalyticsProcessor.cs, Flagsmith.FlagsmithClient/FlagsmithClient.cs, Flagsmith.FlagsmithClient/IAnalyticsProcessor.cs
Implement support for multi-threading processing in the AnalyticsProcessor class.
Also, implements unit tests replicating potential issues. The issues show themselves only with a huge number of threads running concurrently, and at a certain number it is possible to reproduce them systematically, while that number could depend on the machine resources this has been tested on a MAC Book Pro M2 Processor with 16GB and on a PC with Corei7 and 48GB of RAM.
Please refer to this issue https://github.com/Flagsmith/flagsmith-dotnet-client/issues/88 for more context.
=> chore: Implement multi-threading support for analytics Processor

.github/workflows/formatting-and-tests.yml, .github/workflows/release.yml, Flagsmith.FlagsmithClient/Flagsmith.FlagsmithClient.csproj, global.json
This will publish the NuGet package on release.
The NuGet API key used for the publishing is stored in the `NUGET_APIKEY` repo secret.
- Bump package version
- Add release workflow
- Add `global.json` dotnet version
=> feat: Publish NuGet package automatically

Flagsmith.FlagsmithClient/FlagsmithClient.cs
Add `ConfigureAwait(false)` to calls to async tasks, enforcing the use of a default AsyncContext and that way prevent dead-locks due to the use of contexts with a limited number of tasks like the UI Thread, or the Request Handler Thread.
=> fix: Prevent SynchronizationContext deadlock on dotnet framework

Flagsmith.Client.Test/FlagsmithTest.cs, Flagsmith.Client.Test/HttpMocker.cs, Flagsmith.FlagsmithClient/FlagsmithClient.cs
Fixing https://github.com/Flagsmith/flagsmith-dotnet-client/issues/103
- An additional validation was added to avoid always using the offlineHandler document when it is set.
- Added a new test for this specific case
=> fix: OfflineHandler causes the SDK to bypass live flag lookups

Flagsmith.FlagsmithClient/AnalyticsProcessor.cs
This adds ConfigureAwait(false) to AnalyticsProcessor.cs, per https://github.com/Flagsmith/flagsmith-dotnet-client/issues/113.
=> Add ConfigureAwait(false) to AnalyticsProcessor

.github/workflows/release.yml
Supersedes #114 which only updated download-artifact (which is stated as not being backwards compatible with artifacts uploaded with v3 [here](https://github.com/actions/download-artifact/releases/tag/v4.0.0)).
=> deps: bump artifact options

Flagsmith.FlagsmithClient/Flagsmith.FlagsmithClient.csproj
Forgot to bump version before releasing https://github.com/Flagsmith/flagsmith-dotnet-client/releases/tag/v5.4.1
This means 5.3.2 in nuget actually corresponds to the current 5.4.1 - we can fix this later, and releasing 5.4.1 again will now work as we expect.
=> chore: bump version to 5.4.1

Flagsmith.FlagsmithClient/Flagsmith.FlagsmithClient.csproj, Flagsmith.FlagsmithClient/FlagsmithClient.cs
Fixes a deadlock when awaiting the initial poll for local evaluation mode in the `FlagsmithClient` constructor in ASP.NET MVC.
This can be reproduced with the following sample project, by setting a correct server-side environment key here: https://github.com/rolodato/flagsmith-dotnet-mvc-deadlock-repro/blob/18bc0633d1e5c5443c2d79bc2fde5eb10eb880d1/flagsmith-error-repro/Controllers/HomeController.cs#L14. To reproduce, run the solution in Visual Studio and the index page will hang forever. I was not able to reproduce this deadlock on macOS with Mono - it only happened on Windows.
This can be also worked around from the application side by instantiating `FlagsmithClient` in an asynchronous view, but this does not play well with IoC/DI solutions such as [Autofac](https://autofac.org/): …
=> Fix constructor deadlock when using local evaluation

Flagsmith.Client.Test/Fixtures.cs, Flagsmith.Engine/Feature/Models/FeatureStateModel.cs, Flagsmith.FlagsmithClient/Flagsmith.FlagsmithClient.csproj
I'm not sure how `django_id` can return null here, but other SDKs do handle this possibility:
* https://github.com/Flagsmith/flagsmith-ruby-client/blob/d467610cc9ad868082aeb6ce58322dbd3cf669dc/lib/flagsmith/engine/identities/models.rb#L17
* https://github.com/Flagsmith/flagsmith-php-client/blob/7c20db24691fe5a59cc69676733df93bb543255f/src/Engine/Identities/IdentityModel.php#L23
* https://github.com/Flagsmith/flagsmith-engine/blob/902aa899ce156012e6551fe9a8499848ccafdfbf/flag_engine/features/models.py#L78
This caused an exception in the `FlagsmithClient` constructor similar to this:
```
Newtonsoft.Json.JsonSerializationException
HResult=0x80131500
Message=Error converting value {null} to type 'System.Int32'. Path 'identity_overrides[0].identity_features[0].django_id', line 1, position …
```
=> fix: handle null django_id in identity overrides for local evaluation mode

.github/workflows/release.yml, Flagsmith.FlagsmithClient/Flagsmith.FlagsmithClient.csproj
This workflow run was meant to publish version 6.0.0 and succeeded: https://github.com/Flagsmith/flagsmith-dotnet-client/actions/runs/12350235990/job/34462737804
However, the last published version is still 5.4.3: https://www.nuget.org/packages/Flagsmith. This is because we didn't bump the version here before releasing: https://github.com/Flagsmith/flagsmith-dotnet-client/blob/137590cc3fd8d9c2b739d046618631f07ee1068f/Flagsmith.FlagsmithClient/Flagsmith.FlagsmithClient.csproj#L10
The workflow succeeded because it uses `dotnet nuget push --skip-duplicate`. This is intended to handle partial failures when publishing multiple packages at once, which we don't want since we only have one package to publish.
This change also bumps the version to 6.0.0.
Note: this is completely untested!
=> ci: Fail publishing workflow if trying to release a duplicate version + bump to 6.0.0

Flagsmith.FlagsmithClient/Flag.cs, Flagsmith.FlagsmithClient/Flagsmith.FlagsmithClient.csproj, Flagsmith.FlagsmithClient/IFlag.cs
Fixes https://github.com/Flagsmith/flagsmith-dotnet-client/issues/128
I considered making making `Id` nullable, but IMO there's no reason why ID is relevant at all for customers or SDK internals. Removing it is the most future-proof change.
`getFeatureId` is also not used anywhere. `ToString` makes no sense to have as part of the `IFlag` interface.
=> fix!: Remove flag ID properties/methods

Flagsmith.Client.Test/Fixtures.cs, Flagsmith.Client.Test/FlagsmithTest.cs, Flagsmith.FlagsmithClient/FlagsmithClient.cs
Change current Console.log to throw an exception when trying to instantiate the .NET client without a server key.
=> fix!: throw exception on startup when using local evaluation without server key

Flagsmith.Client.Test/Fixtures.cs, Flagsmith.Client.Test/FlagsmithTest.cs, Flagsmith.FlagsmithClient/FlagsmithClient.cs
Reverts Flagsmith/flagsmith-dotnet-client#141
Reverting so that we can first merge this PR, release a 7.1.0, then create an 8.0.0 version which adds this breaking change back, and removes the methods marked for deprecation in #136 .
=> Revert "fix!: throw exception on startup when using local evaluation without server key"

Flagsmith.Client.Test/FlagsmithTest.cs, Flagsmith.Client.Test/FlagsmithTestDeprecated.cs, Flagsmith.Client.Test/PollingManagerTest.cs, Flagsmith.FlagsmithClient/FlagsmithClient.cs, Flagsmith.FlagsmithClient/FlagsmithConfiguration.cs, Flagsmith.FlagsmithClient/IFlagsmithConfiguration.cs, Flagsmith.FlagsmithClient/PollingManager.cs
Fixes https://github.com/Flagsmith/flagsmith-dotnet-client/issues/135.
Validated this does not break existing code by running the existing test suite without changes: https://github.com/Flagsmith/flagsmith-dotnet-client/pull/136/commits/0b41d2b7edcf26ac218f369e399335717637830f
=> feat: Deprecate constructors with >1 parameter and IFlagsmithConfig interface. Add EnableLocalEvaluation and EnvironmentRefreshInterval properties

Flagsmith.Client.Test/FlagsmithTest.cs, Flagsmith.FlagsmithClient/Flagsmith.FlagsmithClient.csproj, Flagsmith.FlagsmithClient/FlagsmithConfiguration.cs
Fixes https://github.com/Flagsmith/flagsmith-dotnet-client/issues/153.
=> fix: Fix default request timeout being 0

Flagsmith.FlagsmithClient/Flags.cs
=> fix: Analytics update is blocking

Flagsmith.FlagsmithClient/Flagsmith.FlagsmithClient.csproj
Resolve issue introduced in #158 by updating to the correct SPDX identifier.
=> chore: update PackageLicenseExpression to conforming SPDK identifier
